### ISSUE TITLE
CRUD Series

### ISSUE THREAD

**Issue by kauelima21** [kauelima21/series-flix#1]

**Comment by kauelima21** [comment]
Suggest schema:

Serie {
	id: string;
	name: string;
	category: string;
	seasons: int;
	rating: float;
}

**Comment by ayrtonmarinho** [comment]
[Question] Esse "rating" é a nota ou a classificação?

**Comment by kauelima21** [comment]
É a avaliação, mas caso queira adicionar outros atributos e eliminar esse, pode fazê-lo a vontade.
